/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.servicentroguerrero.gui;

import co.com.servicentro.util.Util;
import co.com.servicentroguerrero.controler.ControllerBO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author JICZ
 */
public class DineroLiquidacionExtra extends javax.swing.JDialog {


    /**
     * Creates new form DineroLiquidacionExtra
     *
     * @param parent frame padre.
     * @param modal activar modo modal o no.
     */
    public DineroLiquidacionExtra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        /*Asignar los formatos numerico decimal a cada caja de texto*/
        jFormattedTextFieldBauches.setFormatterFactory(Util.formatoNumericoDecimal());
        jFormattedTextFieldBauches.setValue(new Double(0));
        jFormattedTextFieldMoneda.setFormatterFactory(Util.formatoNumericoDecimal());
        jFormattedTextFieldMoneda.setValue(new Double(0));
        jFormattedTextFieldVales.setFormatterFactory(Util.formatoNumericoDecimal());
        jFormattedTextFieldVales.setValue(new Double(0));
        jFormattedTextFieldEfectivo.setFormatterFactory(Util.formatoNumericoDecimal());
        jFormattedTextFieldEfectivo.setValue(new Double(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldBauches = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldMoneda = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldVales = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldEfectivo = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dinero Liquidacion Extra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 3, 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("  Bauches:");
        jPanel1.add(jLabel1);

        jFormattedTextFieldBauches.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldBauches.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldBauches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldBauchesActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldBauches);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("  Moneda:");
        jPanel1.add(jLabel2);

        jFormattedTextFieldMoneda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldMoneda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMonedaActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldMoneda);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("  Vales:");
        jPanel1.add(jLabel3);

        jFormattedTextFieldVales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldVales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldVales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldValesActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldVales);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("  Efectivo:");
        jPanel1.add(jLabel4);

        jFormattedTextFieldEfectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldEfectivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jFormattedTextFieldEfectivo);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            double[] liquidacionExtra = new double[4];
            /*cargar el objeto de liquidacion extra*/
            String sBauches = jFormattedTextFieldBauches.getText().length() == 0? "0.0" : jFormattedTextFieldBauches.getText();
            String sMoneda = jFormattedTextFieldMoneda.getText().length() == 0? "0.0" : jFormattedTextFieldMoneda.getText();
            String sVales = (jFormattedTextFieldVales.getText().length() == 0)? "0.0" : jFormattedTextFieldVales.getText();
            String sEfectivo = jFormattedTextFieldEfectivo.getText().length() == 0? "0.0" : jFormattedTextFieldEfectivo.getText();
            liquidacionExtra[0] = Double.parseDouble(sBauches);
            liquidacionExtra[1] = Double.parseDouble(sMoneda);
            liquidacionExtra[2] = Double.parseDouble(sVales);
            liquidacionExtra[3] = Double.parseDouble(sEfectivo);

            /*guardar la informacion*/
            double ingresado = ControllerBO.guardarLiquidacionExtra(liquidacionExtra);
            if (ingresado > 0) {
                JOptionPane.showMessageDialog(this, "Liquidacion extra insertada de forma correcta.", "Liquidacion Extra", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                throw new HeadlessException("No se registro la liquidacion extra. Intente nuevamente.");
            }
        } catch (HeadlessException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextFieldBauchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBauchesActionPerformed
        jFormattedTextFieldMoneda.setText("");
        jFormattedTextFieldMoneda.requestFocusInWindow();
    }//GEN-LAST:event_jFormattedTextFieldBauchesActionPerformed

    private void jFormattedTextFieldMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMonedaActionPerformed
        jFormattedTextFieldVales.setText("");
        jFormattedTextFieldVales.requestFocusInWindow();
    }//GEN-LAST:event_jFormattedTextFieldMonedaActionPerformed

    private void jFormattedTextFieldValesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldValesActionPerformed
        jFormattedTextFieldEfectivo.setText("");
        jFormattedTextFieldEfectivo.requestFocusInWindow();
    }//GEN-LAST:event_jFormattedTextFieldValesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextFieldBauches;
    private javax.swing.JFormattedTextField jFormattedTextFieldEfectivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldMoneda;
    private javax.swing.JFormattedTextField jFormattedTextFieldVales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
