/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.servicentroguerrero.gui;

import co.com.servicentro.util.DocumentTypeInteger;
import co.com.servicentro.util.Util;
import co.com.servicentroguerrero.controler.ControllerBO;
import co.com.servicentroguerrero.modelos.Combustible;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JICZ4
 */
public class JFrameActualizarPrecios extends javax.swing.JFrame {
    
    /**
     *
     * Constante para indicar una posicion por defecto en combobox.
     */
    private static final int POSITION_DEFAULT = 0x00;
    
    /**
     * Constante para indicar que acepta la accion
     */
    private static final int ACEPTAR = 0X00;
    
    /**
     * Constante para indicar que cancela la accion
     */
    private static final int CANCELAR = 0X02;
    
    /**
     * Lista que contiene los combustibles disponibles;
     */
    private final ArrayList<Combustible> listaCombustibles;
    
     /**
     * Actualizar datos en ventana princilpal
     */
    private final IRefresh refresh;

    /**
     * Creates new form JFrameActualizarPrecios
     * @param iRefresh
     */
    public JFrameActualizarPrecios(IRefresh iRefresh) {
        /*Instanciar la lista de combustibles*/
        this.listaCombustibles = new ArrayList<>();
        initComponents();
        cargarCombustiblesDisponibles();
        jTextFieldnuevoPrecio.setDocument(new DocumentTypeInteger());
        this.refresh = iRefresh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelCombustibles = new javax.swing.JPanel();
        jComboBoxCombustibles = new javax.swing.JComboBox<>();
        jPanelPrecios = new javax.swing.JPanel();
        jPanelPrecioActual = new javax.swing.JPanel();
        jLabelPrecioActual = new javax.swing.JLabel();
        jTextFieldPrecioActual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelNuevoPrecio = new javax.swing.JLabel();
        jTextFieldnuevoPrecio = new javax.swing.JTextField();
        jPanelBotonActualizarPrecios = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Precios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContainer.setLayout(new java.awt.GridLayout(3, 1, 4, 4));

        jPanelCombustibles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Combustible", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jComboBoxCombustibles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxCombustibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCombustiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCombustiblesLayout = new javax.swing.GroupLayout(jPanelCombustibles);
        jPanelCombustibles.setLayout(jPanelCombustiblesLayout);
        jPanelCombustiblesLayout.setHorizontalGroup(
            jPanelCombustiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCombustiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCombustibles, 0, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCombustiblesLayout.setVerticalGroup(
            jPanelCombustiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCombustiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCombustibles, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContainer.add(jPanelCombustibles);

        jPanelPrecios.setLayout(new java.awt.GridLayout(2, 1, 4, 4));

        jPanelPrecioActual.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

        jLabelPrecioActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrecioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecioActual.setText("Combustible");
        jPanelPrecioActual.add(jLabelPrecioActual);

        jTextFieldPrecioActual.setEditable(false);
        jTextFieldPrecioActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecioActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioActual.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecioActual.setEnabled(false);
        jPanelPrecioActual.add(jTextFieldPrecioActual);

        jPanelPrecios.add(jPanelPrecioActual);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

        jLabelNuevoPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNuevoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevoPrecio.setText("Nuevo Precio: ");
        jPanel2.add(jLabelNuevoPrecio);

        jTextFieldnuevoPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldnuevoPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldnuevoPrecio);

        jPanelPrecios.add(jPanel2);

        jPanelContainer.add(jPanelPrecios);

        jPanelBotonActualizarPrecios.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanelBotonActualizarPrecios.add(jPanel1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelBotonActualizarPrecios.add(jButton1);

        jPanelContainer.add(jPanelBotonActualizarPrecios);

        getContentPane().add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCombustiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCombustiblesActionPerformed
        int index = jComboBoxCombustibles.getSelectedIndex();
        if(index != POSITION_DEFAULT){
            jLabelPrecioActual.setText(listaCombustibles.get(index - 1).getCombustible());
            jTextFieldPrecioActual.setText("$" + Util.formatearMiles(listaCombustibles.get(index -1).getPrecioVigente()));
        }
        else {
            jLabelPrecioActual.setText("Combustible");
            jTextFieldPrecioActual.setText("");
        }
    }//GEN-LAST:event_jComboBoxCombustiblesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = jComboBoxCombustibles.getSelectedIndex();
        if(index != POSITION_DEFAULT){
            String sPrecio = jTextFieldnuevoPrecio.getText().trim();
            if(sPrecio.length() > 0 && Util.isNumeric(sPrecio)){
                /*verificar la actualizacion del precio*/
                actualizarNuevoPrecio(index - 1, Double.parseDouble(sPrecio));
            }
            else {
                JOptionPane.showMessageDialog(this, "Ingrese un nuevo precio.", "Error", JOptionPane.ERROR_MESSAGE);
                jTextFieldnuevoPrecio.requestFocusInWindow();
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Selecione un combustible", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * CArgar los combustibles disponibles para actualizar precio.
     */
    private void cargarCombustiblesDisponibles() {
         /*Marcar posicion por defecto y asignarla al combo*/
        jComboBoxCombustibles.insertItemAt("Seleccione Combustible - ", POSITION_DEFAULT);
        jComboBoxCombustibles.setSelectedIndex(POSITION_DEFAULT);

        /*Agregar los items con los datos de los empleados con rol islero.*/
        ControllerBO.cargarCombustibles().forEach((c) -> {
            getListaCombustibles().add(c);
        });
        
        /*Llenar el combobox con los combustibles disponibles*/
        listaCombustibles.forEach((combustible) -> {
            jComboBoxCombustibles.addItem(combustible.getCombustible());
        });        
    }

    
    
    public ArrayList<Combustible> getListaCombustibles() {
        return listaCombustibles;
    }

    private void actualizarNuevoPrecio(final int index, final Double nuevoPrecio) {
        try {
            int option = JOptionPane.showConfirmDialog(this, "Aceptar para actualizar el precio", "¿Actualizar Precio?", JOptionPane.OK_CANCEL_OPTION);
            if (option == ACEPTAR) {
                if(ControllerBO.actualizarPrecioCombustible(listaCombustibles.get(index).getIdCombustible(), nuevoPrecio)){
                    JOptionPane.showMessageDialog(this, "Precio actualizado.", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                    JFrameActualizarPrecios.this.dispose();
                    this.refresh.refrescarVentanaLiquidacion();
                }      
            }
        } catch (Exception ex) {
            Logger.getLogger(JFrameActualizarPrecios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCombustibles;
    private javax.swing.JLabel jLabelNuevoPrecio;
    private javax.swing.JLabel jLabelPrecioActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotonActualizarPrecios;
    private javax.swing.JPanel jPanelCombustibles;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelPrecioActual;
    private javax.swing.JPanel jPanelPrecios;
    private javax.swing.JTextField jTextFieldPrecioActual;
    private javax.swing.JTextField jTextFieldnuevoPrecio;
    // End of variables declaration//GEN-END:variables
}