/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.servicentroguerrero.gui;

import co.com.servicentro.util.Util;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JICZ4
 */
public class JFrameAgregarVales extends javax.swing.JFrame {

    
    private final IVale interfaceVale;
    /**
     * Referencia al modelo que permite asignar datos a la tabla.
     */
    private DefaultTableModel model;

    /**
     * Numero contador - identificador de filas.
     */
    private int rowNumber = 0;

    /**
     * Moto total de vales ingresados.
     */
    private double totalVales = 0;

    /**
     * Creates new form JFrameAgregarVales
     * @param interfaceVale interface para detectar el calculo del total de vales ingresados.
     */
    public JFrameAgregarVales(IVale interfaceVale) {
        this.interfaceVale = interfaceVale;
        initComponents();
        setTableModel();
        /*Asignar el conteo inicial de filas*/
        rowNumber = jTableVales.getColumnCount() - 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVales = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelTotalVales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(2, 300));

        jScrollPane1.setViewportView(jTableVales);
        if (jTableVales.getColumnModel().getColumnCount() > 0) {
            jTableVales.getColumnModel().getColumn(0).setResizable(false);
            jTableVales.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        getContentPane().add(jSeparator1);

        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelTotalVales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalVales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalVales.setText("$0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabelTotalVales, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 15, Short.MAX_VALUE)
                        .addComponent(jLabelTotalVales, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para conservar el total de vales agregados.
     *
     * @param evt
     */
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String ingresado = JOptionPane.showInputDialog(this, "Ingrese el valor del vale:");
        /*Validar que el numero ingresado sea un numero correcto mayor a cero.*/
        if (Util.isNumeric(ingresado) && Double.parseDouble(ingresado) > 0) {
            this.model.addRow(new Object[]{rowNumber, ("$" + Util.formatearMiles(Double.parseDouble(ingresado)))});
            this.rowNumber++;
            this.totalVales += Double.parseDouble(ingresado);
        } else {
            JOptionPane.showMessageDialog(this, ingresado + " -> No es un valor valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jLabelTotalVales.setText("$" + Util.formatearMiles(this.totalVales));
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * Eliminar un vale ingresado.
     *
     * @param evt
     */
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        String ingresado = JOptionPane.showInputDialog(this, "Ingrese el Numero a elimiinar : ");
        /*Si cancela la eliminacion no hacer nada*/
        if (ingresado != null) {
            /*Si ingresa un dato validar que sea valido*/
            if (Util.isNumeric(ingresado)) {
                int index = (Integer.parseInt(ingresado) - 1);
                /*Validar que el dato ingresado este en el rango*/
                if (index >= 0 && index < this.model.getRowCount()) {
                    /*Remover el dato y calcular el nuevo total*/
                    Object data = this.model.getValueAt(index, 1);
                    this.model.removeRow(index);
                    this.totalVales -= Double.parseDouble(data.toString().replace("$", "").replace(".", "").replace(",", "."));
                    this.rowNumber--;
                    
                    /*recalcular el numero de identificacion de filas*/
                    for (int i = 0; i < this.model.getRowCount(); i++) {
                        this.model.setValueAt(String.valueOf(i + 1), i, 0);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, ingresado + " -> No esta en un rango valido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, ingresado + " -> No es un numero valido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            jLabelTotalVales.setText("$" + Util.formatearMiles(this.totalVales));
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    
    /**
     * Entregar a la ventana padre el valor de vales calculados.
     * @param evt 
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.interfaceVale.totalValesCalculados(this.totalVales);
    }//GEN-LAST:event_formWindowClosed

    /**
     * Asignar el modelo a la tabla.
     */
    private void setTableModel() {
        /*Crear el modelo solo si no se ha asignado uno antes.*/
        if (this.model == null) {
            this.model = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"Numero", "Valor"}
            ) {
                /*Inpedir que se puedan editar los valores ingresados*/
                boolean[] canEdit = new boolean[]{
                    false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            jTableVales.setModel(this.model);
        }
    }

    /**
     * Entregar el total de vales ingresados
     *
     * @return
     */
    public double getTotalVales() {
        return totalVales;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelTotalVales;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableVales;
    // End of variables declaration//GEN-END:variables
}
