/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.servicentroguerrero.gui;

import co.com.servicentro.util.DocumentTypeInteger;
import co.com.servicentro.util.Util;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.ImageIcon;

/**
 *
 * @author JICZ4
 */
public class JFrameIngresoDinero extends javax.swing.JFrame implements IVale{

   
    /* Contantes para identificar las diferentes denominaciones de billetes 
    en pesos COP.*/
    private static final int CIEN_MIL = 100000;
    private static final int CINCUENTA_MIL = 50000;
    private static final int VEINTE_MIL = 20000;
    private static final int DIEZ_MIL = 10000;
    private static final int CINCO_MIL = 5000;
    private static final int DOS_MIL = 2000;
    private static final int UN_MIL = 1000;
    
    /**
     * Variable que conserva el total de didero ingresado.
     */
    private double totalDinero = 0;
    
    /**
     * totalizado de denominacion de cien mil
     */
    private double totalCienMil = 0;
    
    /**
     * totalizado de denominacion de cincuenta mil
     */
    private double totalCincuentaMil = 0;
    
    /**
     * totalizado de denominacion de veinte mil
     */
    private double totalVeinteMil = 0;
    
    /**
     * totalizado de denominacion de diez mil
     */
    private double totalDiezMil = 0;
    
    /**
     * totalizado de denominacion de cinco mil
     */
    private double totalCincoMil = 0;
    
    /**
     * totalizado de denominacion de dos mil
     */
    private double totalDosMil = 0;
    
    
    /**
     * totalizado de denominacion de mil
     */
    private double totalMil = 0;
    
    /**
     * totalizado de denominacion de bauches
     */
    private double totalBauches = 0;
    
    /**
     * totalizado de denominacion de vales
     */
    private double totalVales = 0;
    
    /**
     * totalizado de denominacion de monedas
     */
    private double totalMonedas = 0;
    
    /**
     * totalizado de denominacion de efectivos
     */
    private double totalEfectivos = 0;
    
    
    private JFrameAgregarVales jFrameAgregarVales;
    
    /**
     * Creates new form JFrameIngresoDinero
     */
    public JFrameIngresoDinero() {
        initComponents();
        setDocumentsNumeric();
        cargarIconoBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelcontenedorEntregaDinero = new javax.swing.JPanel();
        jPanelContenedorTitulos = new javax.swing.JPanel();
        jPanelDenominacion = new javax.swing.JPanel();
        jLabelDenominacion = new javax.swing.JLabel();
        jPanelCantidad = new javax.swing.JPanel();
        jLabelCantidad = new javax.swing.JLabel();
        jPanelValor = new javax.swing.JPanel();
        jLabelValor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelContenidoEntregaDinero = new javax.swing.JPanel();
        jPanel100000 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCienMil = new javax.swing.JTextField();
        jLabelCienMil = new javax.swing.JLabel();
        jPanel50000 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCincuentaMil = new javax.swing.JTextField();
        jLabelCincuentaMil = new javax.swing.JLabel();
        jPanel20000 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldVeinteMil = new javax.swing.JTextField();
        jLabelVeinteMil = new javax.swing.JLabel();
        jPanel10000 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDiezMil = new javax.swing.JTextField();
        jLabelDiezMil = new javax.swing.JLabel();
        jPanel5000 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCincoMil = new javax.swing.JTextField();
        jLabelCincoMil = new javax.swing.JLabel();
        jPanel2000 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDosMil = new javax.swing.JTextField();
        jLabelDosMil = new javax.swing.JLabel();
        jPanel1000 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMil = new javax.swing.JTextField();
        jLabelMil = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelOtrasDenominaciones = new javax.swing.JPanel();
        jPanelBauches = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBauches = new javax.swing.JTextField();
        jPanelVales = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldVales = new javax.swing.JTextField();
        jButtonAgregarVale = new javax.swing.JButton();
        jPanelMoneda = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMoneda = new javax.swing.JTextField();
        jPanelEfectivo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldEfectivos = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelTotalizado = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotalDineroRecibido = new javax.swing.JLabel();

        setTitle("Entrega de Dinero");
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelcontenedorEntregaDinero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrega de Dinero", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanelContenedorTitulos.setLayout(new java.awt.GridLayout(1, 3, 1, 1));

        jLabelDenominacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDenominacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDenominacion.setText("Denominacion");

        javax.swing.GroupLayout jPanelDenominacionLayout = new javax.swing.GroupLayout(jPanelDenominacion);
        jPanelDenominacion.setLayout(jPanelDenominacionLayout);
        jPanelDenominacionLayout.setHorizontalGroup(
            jPanelDenominacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDenominacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDenominacionLayout.setVerticalGroup(
            jPanelDenominacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDenominacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelContenedorTitulos.add(jPanelDenominacion);

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidad.setText("Cantidad");

        javax.swing.GroupLayout jPanelCantidadLayout = new javax.swing.GroupLayout(jPanelCantidad);
        jPanelCantidad.setLayout(jPanelCantidadLayout);
        jPanelCantidadLayout.setHorizontalGroup(
            jPanelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCantidadLayout.setVerticalGroup(
            jPanelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelContenedorTitulos.add(jPanelCantidad);

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValor.setText("Valor");

        javax.swing.GroupLayout jPanelValorLayout = new javax.swing.GroupLayout(jPanelValor);
        jPanelValor.setLayout(jPanelValorLayout);
        jPanelValorLayout.setHorizontalGroup(
            jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelValorLayout.setVerticalGroup(
            jPanelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelContenedorTitulos.add(jPanelValor);

        jPanelContenidoEntregaDinero.setMaximumSize(new java.awt.Dimension(67, 67));
        jPanelContenidoEntregaDinero.setLayout(new java.awt.GridLayout(7, 1, 1, 1));

        jPanel100000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("$100.000");
        jPanel100000.add(jLabel3);

        jTextFieldCienMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCienMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCienMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCienMilFocusLost(evt);
            }
        });
        jTextFieldCienMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCienMilActionPerformed(evt);
            }
        });
        jPanel100000.add(jTextFieldCienMil);

        jLabelCienMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCienMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCienMil.setText("0");
        jPanel100000.add(jLabelCienMil);

        jPanelContenidoEntregaDinero.add(jPanel100000);

        jPanel50000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("$50.000");
        jPanel50000.add(jLabel2);

        jTextFieldCincuentaMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCincuentaMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCincuentaMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCincuentaMilFocusLost(evt);
            }
        });
        jTextFieldCincuentaMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCincuentaMilActionPerformed(evt);
            }
        });
        jPanel50000.add(jTextFieldCincuentaMil);

        jLabelCincuentaMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCincuentaMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCincuentaMil.setText("0");
        jPanel50000.add(jLabelCincuentaMil);

        jPanelContenidoEntregaDinero.add(jPanel50000);

        jPanel20000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$20.000");
        jPanel20000.add(jLabel4);

        jTextFieldVeinteMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldVeinteMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVeinteMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldVeinteMilFocusLost(evt);
            }
        });
        jTextFieldVeinteMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVeinteMilActionPerformed(evt);
            }
        });
        jPanel20000.add(jTextFieldVeinteMil);

        jLabelVeinteMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelVeinteMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVeinteMil.setText("0");
        jPanel20000.add(jLabelVeinteMil);

        jPanelContenidoEntregaDinero.add(jPanel20000);

        jPanel10000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$10.000");
        jPanel10000.add(jLabel6);

        jTextFieldDiezMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDiezMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDiezMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDiezMilFocusLost(evt);
            }
        });
        jTextFieldDiezMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiezMilActionPerformed(evt);
            }
        });
        jPanel10000.add(jTextFieldDiezMil);

        jLabelDiezMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelDiezMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiezMil.setText("0");
        jPanel10000.add(jLabelDiezMil);

        jPanelContenidoEntregaDinero.add(jPanel10000);

        jPanel5000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("$5.000");
        jPanel5000.add(jLabel8);

        jTextFieldCincoMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCincoMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCincoMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCincoMilFocusLost(evt);
            }
        });
        jTextFieldCincoMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCincoMilActionPerformed(evt);
            }
        });
        jPanel5000.add(jTextFieldCincoMil);

        jLabelCincoMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCincoMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCincoMil.setText("0");
        jPanel5000.add(jLabelCincoMil);

        jPanelContenidoEntregaDinero.add(jPanel5000);

        jPanel2000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("$2.000");
        jPanel2000.add(jLabel10);

        jTextFieldDosMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDosMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDosMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDosMilFocusLost(evt);
            }
        });
        jTextFieldDosMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDosMilActionPerformed(evt);
            }
        });
        jPanel2000.add(jTextFieldDosMil);

        jLabelDosMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelDosMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDosMil.setText("0");
        jPanel2000.add(jLabelDosMil);

        jPanelContenidoEntregaDinero.add(jPanel2000);

        jPanel1000.setLayout(new java.awt.GridLayout(1, 3));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("$1.000");
        jPanel1000.add(jLabel12);

        jTextFieldMil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMilFocusLost(evt);
            }
        });
        jTextFieldMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMilActionPerformed(evt);
            }
        });
        jPanel1000.add(jTextFieldMil);

        jLabelMil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelMil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMil.setText("0");
        jPanel1000.add(jLabelMil);

        jPanelContenidoEntregaDinero.add(jPanel1000);

        jPanelOtrasDenominaciones.setLayout(new java.awt.GridLayout(4, 2, 1, 2));

        jPanelBauches.setLayout(new java.awt.GridLayout(1, 2));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Bauches: ");
        jPanelBauches.add(jLabel13);

        jTextFieldBauches.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBauches.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBauches.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBauchesFocusLost(evt);
            }
        });
        jTextFieldBauches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBauchesActionPerformed(evt);
            }
        });
        jPanelBauches.add(jTextFieldBauches);

        jPanelOtrasDenominaciones.add(jPanelBauches);

        jPanelVales.setLayout(new java.awt.GridLayout(1, 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Vales: ");
        jPanelVales.add(jLabel14);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTextFieldVales.setEditable(false);
        jTextFieldVales.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldVales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVales.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldVales.setEnabled(false);
        jTextFieldVales.setFocusable(false);
        jTextFieldVales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValesFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jTextFieldVales, gridBagConstraints);

        jButtonAgregarVale.setText("  ");
        jButtonAgregarVale.setAlignmentY(0.0F);
        jButtonAgregarVale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonAgregarVale.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgregarVale.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonAgregarVale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarValeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jButtonAgregarVale, gridBagConstraints);

        jPanelVales.add(jPanel3);

        jPanelOtrasDenominaciones.add(jPanelVales);

        jPanelMoneda.setLayout(new java.awt.GridLayout(1, 2));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Moneda: ");
        jPanelMoneda.add(jLabel15);

        jTextFieldMoneda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldMoneda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMoneda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMonedaFocusLost(evt);
            }
        });
        jTextFieldMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonedaActionPerformed(evt);
            }
        });
        jPanelMoneda.add(jTextFieldMoneda);

        jPanelOtrasDenominaciones.add(jPanelMoneda);

        jPanelEfectivo.setLayout(new java.awt.GridLayout(1, 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Otros: ");
        jPanelEfectivo.add(jLabel16);

        jTextFieldEfectivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEfectivos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldEfectivos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEfectivosFocusLost(evt);
            }
        });
        jTextFieldEfectivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEfectivosActionPerformed(evt);
            }
        });
        jPanelEfectivo.add(jTextFieldEfectivos);

        jPanelOtrasDenominaciones.add(jPanelEfectivo);

        jPanelTotalizado.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TOTAL: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTotalizado.add(jPanel1);

        jLabelTotalDineroRecibido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotalDineroRecibido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalDineroRecibido.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTotalDineroRecibido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTotalDineroRecibido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTotalizado.add(jPanel2);

        javax.swing.GroupLayout jPanelcontenedorEntregaDineroLayout = new javax.swing.GroupLayout(jPanelcontenedorEntregaDinero);
        jPanelcontenedorEntregaDinero.setLayout(jPanelcontenedorEntregaDineroLayout);
        jPanelcontenedorEntregaDineroLayout.setHorizontalGroup(
            jPanelcontenedorEntregaDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcontenedorEntregaDineroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelcontenedorEntregaDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTotalizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jPanelContenedorTitulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContenidoEntregaDinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOtrasDenominaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        jPanelcontenedorEntregaDineroLayout.setVerticalGroup(
            jPanelcontenedorEntregaDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcontenedorEntregaDineroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedorTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContenidoEntregaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOtrasDenominaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTotalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelcontenedorEntregaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelcontenedorEntregaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    /**
     * Evento para llevar el focus al siguientes text al hacer enter.
     * @param evt 
     */
    private void jTextFieldCincuentaMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCincuentaMilActionPerformed
        jTextFieldVeinteMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldCincuentaMilActionPerformed

    private void jTextFieldVeinteMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVeinteMilActionPerformed
        jTextFieldDiezMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldVeinteMilActionPerformed

    private void jTextFieldDiezMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiezMilActionPerformed
        jTextFieldCincoMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldDiezMilActionPerformed

    private void jTextFieldCincoMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCincoMilActionPerformed
        jTextFieldDosMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldCincoMilActionPerformed

    private void jTextFieldDosMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDosMilActionPerformed
        jTextFieldMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldDosMilActionPerformed

    private void jTextFieldMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMilActionPerformed
        jTextFieldBauches.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldMilActionPerformed

    private void jTextFieldBauchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBauchesActionPerformed
        jTextFieldMoneda.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldBauchesActionPerformed

    private void jTextFieldMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonedaActionPerformed
        jTextFieldEfectivos.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldMonedaActionPerformed

    private void jTextFieldEfectivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEfectivosActionPerformed
        this.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldEfectivosActionPerformed

    private void jTextFieldCincuentaMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCincuentaMilFocusLost
        // TODO add your handling code here:
        String text = jTextFieldCincuentaMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalCincuentaMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), CINCUENTA_MIL);
                jLabelCincuentaMil.setText("$" + Util.formatearMiles(this.totalCincuentaMil));
            }
        }
        else {
            jLabelCincuentaMil.setText("$" + Util.formatearMiles(0));
            this.totalCincuentaMil = 0;
        }
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldCincuentaMilFocusLost

    private void jTextFieldVeinteMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldVeinteMilFocusLost
        String text = jTextFieldVeinteMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalVeinteMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), VEINTE_MIL);
                jLabelVeinteMil.setText("$" + Util.formatearMiles(this.totalVeinteMil));
            }
        }
        else {
            jLabelVeinteMil.setText("$" + Util.formatearMiles(0));
            this.totalVeinteMil = 0;
        }  
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldVeinteMilFocusLost

    private void jTextFieldDiezMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDiezMilFocusLost
        String text = jTextFieldDiezMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalDiezMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), DIEZ_MIL);
                jLabelDiezMil.setText("$" + Util.formatearMiles(this.totalDiezMil));
            }
        }
        else {
            jLabelDiezMil.setText("$" + Util.formatearMiles(0));
            this.totalDiezMil = 0;
        }  
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldDiezMilFocusLost

    private void jTextFieldCincoMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCincoMilFocusLost
         String text = jTextFieldCincoMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalCincoMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), CINCO_MIL);
                jLabelCincoMil.setText("$" + Util.formatearMiles(this.totalCincoMil));
            }
        }
        else {
            jLabelCincoMil.setText("$" + Util.formatearMiles(0));
            this.totalCincoMil = 0;
        }  
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldCincoMilFocusLost

    private void jTextFieldDosMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDosMilFocusLost
         String text = jTextFieldDosMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalDosMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), DOS_MIL);
                jLabelDosMil.setText("$" + Util.formatearMiles(this.totalDosMil));
            }
        }
        else {
            jLabelDosMil.setText("$" + Util.formatearMiles(0));
            this.totalDosMil = 0;
        }  
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldDosMilFocusLost

    private void jTextFieldMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMilFocusLost
         String text = jTextFieldMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), UN_MIL);
                jLabelMil.setText("$" + Util.formatearMiles(this.totalMil));
            }
        }
        else {
            jLabelMil.setText("$" + Util.formatearMiles(0));
            this.totalMil = 0;
        } 
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldMilFocusLost

    private void jTextFieldBauchesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBauchesFocusLost
         String text = jTextFieldBauches.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalBauches = Double.parseDouble(text);
            }
            else {
                this.totalBauches = 0;
            }
        }
        else {
            this.totalBauches = 0;
        } 
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldBauchesFocusLost

    private void jTextFieldMonedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMonedaFocusLost
        String text = jTextFieldMoneda.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalMonedas = Double.parseDouble(text);
            }
            else {
                this.totalMonedas = 0;
            }
        }
        else {
            this.totalMonedas = 0;
        } 
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldMonedaFocusLost

    private void jTextFieldEfectivosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEfectivosFocusLost
        String text = jTextFieldEfectivos.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalEfectivos = Double.parseDouble(text);
            }
            else {
                this.totalEfectivos = 0;
            }
        }
        else {
            this.totalEfectivos = 0;
        } 
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldEfectivosFocusLost

    private void jTextFieldCienMilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCienMilFocusLost
        // TODO add your handling code here:
        String text = jTextFieldCienMil.getText().trim();
        /*Si contiene texto iniciar calculo de monto de denominacion */
        if(text != null && text.length() > 0){
            if(Util.isNumeric(text)){
                this.totalCienMil = Util.calcularMontoPorDenominacion(Integer.parseInt(text), CIEN_MIL);
                jLabelCienMil.setText("$" + Util.formatearMiles(this.totalCienMil));
            }
        }
        else {
            jLabelCienMil.setText("$" + Util.formatearMiles(0));
            this.totalCienMil = 0;
        }
        calcularTotalDinero();
    }//GEN-LAST:event_jTextFieldCienMilFocusLost

    private void jTextFieldCienMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCienMilActionPerformed
        jTextFieldCincuentaMil.requestFocusInWindow();
    }//GEN-LAST:event_jTextFieldCienMilActionPerformed

    private void jTextFieldValesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValesFocusLost
        
    }//GEN-LAST:event_jTextFieldValesFocusLost

    private void jButtonAgregarValeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarValeActionPerformed
        if(jFrameAgregarVales == null){
            jFrameAgregarVales = new JFrameAgregarVales(this);
            jFrameAgregarVales.setLocationRelativeTo(this);
        }
        jFrameAgregarVales.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarValeActionPerformed

     
    /**
     * Asignar validacion para aceptar unicamente numeros.
     * debe ser una instancia del Document por textField
     */
    private void setDocumentsNumeric() {
        jTextFieldBauches.setDocument(new DocumentTypeInteger());
        jTextFieldCincoMil.setDocument(new DocumentTypeInteger());
        jTextFieldCincuentaMil.setDocument(new DocumentTypeInteger());
        jTextFieldDiezMil.setDocument(new DocumentTypeInteger());
        jTextFieldDosMil.setDocument(new DocumentTypeInteger());
        jTextFieldEfectivos.setDocument(new DocumentTypeInteger());
        jTextFieldMil.setDocument(new DocumentTypeInteger());
        jTextFieldMoneda.setDocument(new DocumentTypeInteger());
        jTextFieldVeinteMil.setDocument(new DocumentTypeInteger());
    }
    
    
    /**
     * Calcular el dinero ingresado y mostrarlo en pantalla.
     */
    private void calcularTotalDinero(){
           this.totalDinero =   this.totalCienMil +
                                this.totalCincuentaMil +
                                this.totalVeinteMil +
                                this.totalDiezMil +
                                this.totalCincoMil +
                                this.totalDosMil +
                                this.totalMil +
                                this.totalBauches +
                                this.totalVales +
                                this.totalMonedas +
                                this.totalEfectivos;
           jLabelTotalDineroRecibido.setText("$" + Util.formatearMiles(this.totalDinero));
    }

    
    /**
     * Get total de dinero ingresado.
     * @return 
     */
    public double getTotalDinero() {
        return totalDinero;
    }
    
    
    private void cargarIconoBoton() {
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/co/com/servicentroguerrero/gui/add.png"));
        Image image = icon.getImage();
        Image imgMetarRes = image.getScaledInstance(25, 30, java.awt.Image.SCALE_SMOOTH);
        jButtonAgregarVale.setMargin(new Insets(0, 0, 0, 0));
        jButtonAgregarVale.setBorder(null);
        jButtonAgregarVale.setIcon(new ImageIcon(imgMetarRes));
    }

    @Override
    public void totalValesCalculados(double totalValesCalculados) {
        this.totalVales = totalValesCalculados;
        jTextFieldVales.setText("$" + Util.formatearMiles(this.totalVales));
        calcularTotalDinero();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarVale;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCienMil;
    private javax.swing.JLabel jLabelCincoMil;
    private javax.swing.JLabel jLabelCincuentaMil;
    private javax.swing.JLabel jLabelDenominacion;
    private javax.swing.JLabel jLabelDiezMil;
    private javax.swing.JLabel jLabelDosMil;
    private javax.swing.JLabel jLabelMil;
    private javax.swing.JLabel jLabelTotalDineroRecibido;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelVeinteMil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1000;
    private javax.swing.JPanel jPanel10000;
    private javax.swing.JPanel jPanel100000;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2000;
    private javax.swing.JPanel jPanel20000;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5000;
    private javax.swing.JPanel jPanel50000;
    private javax.swing.JPanel jPanelBauches;
    private javax.swing.JPanel jPanelCantidad;
    private javax.swing.JPanel jPanelContenedorTitulos;
    private javax.swing.JPanel jPanelContenidoEntregaDinero;
    private javax.swing.JPanel jPanelDenominacion;
    private javax.swing.JPanel jPanelEfectivo;
    private javax.swing.JPanel jPanelMoneda;
    private javax.swing.JPanel jPanelOtrasDenominaciones;
    private javax.swing.JPanel jPanelTotalizado;
    private javax.swing.JPanel jPanelVales;
    private javax.swing.JPanel jPanelValor;
    private javax.swing.JPanel jPanelcontenedorEntregaDinero;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldBauches;
    private javax.swing.JTextField jTextFieldCienMil;
    private javax.swing.JTextField jTextFieldCincoMil;
    private javax.swing.JTextField jTextFieldCincuentaMil;
    private javax.swing.JTextField jTextFieldDiezMil;
    private javax.swing.JTextField jTextFieldDosMil;
    private javax.swing.JTextField jTextFieldEfectivos;
    private javax.swing.JTextField jTextFieldMil;
    private javax.swing.JTextField jTextFieldMoneda;
    private javax.swing.JTextField jTextFieldVales;
    private javax.swing.JTextField jTextFieldVeinteMil;
    // End of variables declaration//GEN-END:variables
}
