/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.servicentroguerrero.gui;

import co.com.servicentro.util.DocumentTypeDouble;
import co.com.servicentro.util.DocumentTypeInteger;
import co.com.servicentroguerrero.controler.ControllerBO;
import co.com.servicentroguerrero.modelos.Combustible;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author JICZ4
 */
public class JFrameActualizarPreciosPlanta extends javax.swing.JFrame {

    /**
     *
     * Constante para indicar una posicion por defecto en combobox.
     */
    private static final int POSITION_DEFAULT = 0x00;

    /**
     * Constante para indicar que acepta la accion
     */
    private static final int ACEPTAR = 0X00;

    /**
     * Constante para indicar que cancela la accion
     */
    private static final int CANCELAR = 0X02;

    /**
     * Lista que contiene los combustibles disponibles;
     */
    private final ArrayList<Combustible> listaCombustibles;

    /**
     * Creates new form JFrameActualizarPrecios
     */
    public JFrameActualizarPreciosPlanta() {
        /*Instanciar la lista de combustibles*/
        this.listaCombustibles = new ArrayList<>();
        initComponents();
        /*habilitar numeros double en los textfield*/
        jTextFieldPrecioAcpm.setDocument(new DocumentTypeDouble());
        jTextFieldPrecioCorriente.setDocument(new DocumentTypeDouble());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelPrecios = new javax.swing.JPanel();
        jPanelPrecioActual = new javax.swing.JPanel();
        jLabelPrecioActual = new javax.swing.JLabel();
        jTextFieldPrecioCorriente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelNuevoPrecio = new javax.swing.JLabel();
        jTextFieldPrecioAcpm = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Precios Compra");

        jPanelPrecios.setLayout(new java.awt.GridLayout(2, 1, 4, 4));

        jPanelPrecioActual.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

        jLabelPrecioActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrecioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecioActual.setText("Precio Compra Corriente: ");
        jPanelPrecioActual.add(jLabelPrecioActual);

        jTextFieldPrecioCorriente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecioCorriente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioCorriente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanelPrecioActual.add(jTextFieldPrecioCorriente);

        jPanelPrecios.add(jPanelPrecioActual);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 3, 3));

        jLabelNuevoPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNuevoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevoPrecio.setText("Precio Compra ACPM:");
        jPanel2.add(jLabelNuevoPrecio);

        jTextFieldPrecioAcpm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPrecioAcpm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldPrecioAcpm);

        jPanelPrecios.add(jPanel2);

        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addComponent(jPanelPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        try {
            String sPrecioCorriente = jTextFieldPrecioCorriente.getText().trim();
            String sPrecioAcpm = jTextFieldPrecioAcpm.getText().trim();
            if (ControllerBO.actualizarPrecioCombustiblePlanta(sPrecioCorriente, sPrecioAcpm) > 0) {
                jTextFieldPrecioCorriente.setText("");
                jTextFieldPrecioAcpm.setText("");
                JOptionPane.showMessageDialog(this, "Precios actualizados de forma correcta.", "ACTUALIZADO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JLabel jLabelNuevoPrecio;
    private javax.swing.JLabel jLabelPrecioActual;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelPrecioActual;
    private javax.swing.JPanel jPanelPrecios;
    private javax.swing.JTextField jTextFieldPrecioAcpm;
    private javax.swing.JTextField jTextFieldPrecioCorriente;
    // End of variables declaration//GEN-END:variables
}
